/*
 *
 * ConnectorClusteringParentAlgorithm.cc source template automatically generated by a class generator
 * Creation date : jeu. f�vr. 20 2014
 *
 * This file is part of ArborPFA libraries.
 * 
 * ArborPFA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * ArborPFA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with ArborPFA.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @author Manqi Ruan
 * @author Henri Videau
 * @copyright CNRS , IPNL
 */


#include "arborpfa/algorithm/ConnectorClusteringParentAlgorithm.h"

// arbor
#include "arborpfa/arbor/AlgorithmHeaders.h"

// pandora
#include "Pandora/PandoraInternal.h"

namespace arbor
{

//----------------------------------------------------------------------------------------------------------------------

pandora::StatusCode ConnectorClusteringParentAlgorithm::RunArborAlgorithm()
{
	std::string oldObjectListName;

	if(!m_objectListName.empty())
	{
		PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::GetCurrentObjectListName(*this, oldObjectListName));
		PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::ReplaceCurrentObjectList(*this, m_objectListName));
	}

	// create connectors and clean them in a algorithm or a series of algorithms
 PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::RunDaughterAlgorithm(*this, m_connectorAlgorithmName));

 const arbor::ClusterList *pClusterList = NULL;
	// build trees and clusters in an algorithm
 PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::RunClusterCreationAlgorithm(*this, m_clusteringAlgorithmName, pClusterList));

 // Run the topological association algorithms to modify clusters
 if (!pClusterList->empty() && !m_associationAlgorithmName.empty())
     PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, PandoraContentApi::RunDaughterAlgorithm(*this, m_associationAlgorithmName));

 if (!pClusterList->empty())
 {
		PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::SaveClusterList(*this, m_clusterListName));

		if (m_replaceCurrentClusterList)
		{
			PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::ReplaceCurrentClusterList(*this, m_clusterListName));
		}
 }

 if(m_restoreOriginalObjectList && !oldObjectListName.empty())
 {
		PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, ArborContentApi::ReplaceCurrentObjectList(*this, oldObjectListName));
 }

	return pandora::STATUS_CODE_SUCCESS;
}

////----------------------------------------------------------------------------------------------------------------------
//
//pandora::StatusCode ArborConnectorClusteringAlgorithm::DrawConnectors() const
//{
//
//	if(!gEve)
//		return STATUS_CODE_SUCCESS;
//
//	TEveElement *pParentCollection = new TEveArrow();
//
//	for(ObjectList::const_iterator objIter = m_pObjectList->begin() , objEndIter = m_pObjectList->end() ; objEndIter != objIter ; ++objIter)
//	{
//		Object *pObject = *objIter;
//		const ConnectorList &connectorList = pObject->GetForwardConnectorList();
//
//		for(ConnectorList::const_iterator iter = connectorList.begin() , endIter = connectorList.end() ; endIter != iter ; ++iter)
//		{
//			Connector *pConnector = *iter;
//			const Object *pOtherObject = NULL;
//
//			if(pObject == pConnector->GetFirst())
//			{
//				pOtherObject = pConnector->GetSecond();
//			}
//			else
//			{
//				pOtherObject = pConnector->GetFirst();
//			}
//
//			CartesianVector fromPosition = pObject->GetPosition();
//			CartesianVector toPosition = pOtherObject->GetPosition();
//
//			PANDORA_THROW_RESULT_IF(STATUS_CODE_SUCCESS, !=, this->DrawEveArrow(pParentCollection, fromPosition, toPosition, kRed));
//		}
//	}
//
//	// add the connector collection to visual monitoring
//	gEve->AddElement(pParentCollection);
//
//	return STATUS_CODE_SUCCESS;
//}
//
////----------------------------------------------------------------------------------------------------------------------
//
//pandora::StatusCode ArborConnectorClusteringAlgorithm::DrawEveArrow(TEveElement *pParentCollection, const pandora::CartesianVector &from, const pandora::CartesianVector &to, int color) const
//{
//
// if(0 == gEve)
// 	return STATUS_CODE_NOT_INITIALIZED;
//
//	const CartesianVector differenceVector = to - from;
//
//	TEveArrow *pEveArrow = new TEveArrow(differenceVector.GetX()/10.0, differenceVector.GetY()/10.0, differenceVector.GetZ()/10.0,
//			                                  from.GetX()/10.0, from.GetY()/10.0, from.GetZ()/10.0);
//	pEveArrow->SetMainColor(color);
//	pEveArrow->SetPickable(true);
//
//	if(NULL != pParentCollection)
//	{
//		pParentCollection->AddElement(pEveArrow);
//	}
//	else
//	{
//	 gEve->AddElement(pEveArrow);
//	}
//	return STATUS_CODE_SUCCESS;
//}

//----------------------------------------------------------------------------------------------------------------------

pandora::StatusCode ConnectorClusteringParentAlgorithm::ReadSettings(const pandora::TiXmlHandle xmlHandle)
{
	m_replaceCurrentClusterList = true;
	PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
	     "ReplaceCurrentClusterList", m_replaceCurrentClusterList));

	m_restoreOriginalObjectList = true;
	PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
	     "RestoreOriginalObjectList", m_restoreOriginalObjectList));

	m_objectListName = "";
	PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ReadValue(xmlHandle,
	     "ObjectListName", m_objectListName));

	m_clusterListName = "ArborClusters";
	PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, pandora::XmlHelper::ReadValue(xmlHandle,
	     "ClusterListName", m_clusterListName));

 // Daughter connector iteration algorithm
 PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, pandora::XmlHelper::ProcessAlgorithm(*this, xmlHandle,
     "ConnectorIteration", m_connectorAlgorithmName));

 // Daughter clustering algorithm
 PANDORA_RETURN_RESULT_IF(pandora::STATUS_CODE_SUCCESS, !=, pandora::XmlHelper::ProcessAlgorithm(*this, xmlHandle,
     "ClusterFormation", m_clusteringAlgorithmName));

 // Daughter association algorithm
 PANDORA_RETURN_RESULT_IF_AND_IF(pandora::STATUS_CODE_SUCCESS, pandora::STATUS_CODE_NOT_FOUND, !=, pandora::XmlHelper::ProcessAlgorithm(*this, xmlHandle,
     "TopologicalAssociation", m_associationAlgorithmName));

	return pandora::STATUS_CODE_SUCCESS;
}


} 

