/*
 *
 * ArborAlgorithm.h header template automatically generated by a class generator
 * Creation date : lun. f�vr. 10 2014
 *
 * This file is part of ArborPFA libraries.
 * 
 * ArborPFA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * ArborPFA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with ArborPFA.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef ARBORALGORITHM_H
#define ARBORALGORITHM_H

#include "Pandora/Algorithm.h"

#include "Pandora/PandoraInputTypes.h"
#include "Pandora/PandoraInternal.h"

#include "arborpfa/arbor/Arbor.h"
#include "arborpfa/api/ArborContentApiImpl.h"

namespace arborpfa {

class ArborAlgorithmFactory;

/** 
 * @brief ArborAlgorithm class
 */ 
class ArborAlgorithm : public pandora::Algorithm
{
 public:

		/**
			* @brief Constructor
			*/
		ArborAlgorithm();

		/**
			* @brief Destructor
			*/
		virtual ~ArborAlgorithm();

		/**
		 *
		 */
		const Arbor *GetArbor() const;

		/**
		 *
		 */
		const ArborContentApiImpl *GetArborContentApiImpl() const;

 protected:

		/**
			*  @brief  Run the algorithm
			*/
		virtual pandora::StatusCode Run() = 0;

		/**
			*  @brief  Read the algorithm settings
			*
			*  @param  xmlHandle the relevant xml handle
			*/
		virtual pandora::StatusCode ReadSettings(const pandora::TiXmlHandle xmlHandle) = 0;

		/**
			*
			*/
		pandora::StatusCode RegisterArbor(Arbor *pArbor);


		Arbor     *m_pArbor;          ///< The arbor instance to run this algorithm

		friend class ArborAlgorithmFactory;

};




} 

#endif  //  ARBORALGORITHM_H
