  /// \file IsolatedHitMergingAlgorithm.h
/*
 *
 * IsolatedHitMergingAlgorithm.h header template automatically generated by a class generator
 * Creation date : dim. f�vr. 9 2014
 *
 * This file is part of ArborPFA libraries.
 * 
 * ArborPFA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * ArborPFA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with ArborPFA.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef ISOLATEDHITMERGINGALGORITHM_H
#define ISOLATEDHITMERGINGALGORITHM_H

// pandora
#include "arborpfa/algorithm/ArborAlgorithm.h"
#include "arborpfa/algorithm/ArborAlgorithmFactory.h"

namespace arborpfa
{

/** 
 * @brief IsolatedHitMergingAlgorithm class
 */ 
class IsolatedHitMergingAlgorithm : public ArborAlgorithm
{
 public:

		/**
			* @brief Factory class for instantiating algorithm
			*/
		class Factory: public ArborAlgorithmFactory
		{
			public:
			ArborAlgorithm *CreateArborAlgorithm() const;
		};

		/**
			* @brief Run the algorithm
			*/
		virtual pandora::StatusCode Run();

		/**
			* @brief Read settings from Xml handler
			*/
		virtual pandora::StatusCode ReadSettings(const pandora::TiXmlHandle xmlHandle);

 protected:

		/**
			* @brief Return the closest distance to cluster
			*/
		float GetClosestDistanceToCluster(const pandora::Cluster *pCluster, const pandora::CaloHit *pCaloHit) const;

}; 

//-------------------------------------------------------------------------------------------------------

ArborAlgorithm *IsolatedHitMergingAlgorithm::Factory::CreateArborAlgorithm() const
{
	return new IsolatedHitMergingAlgorithm();
}

} 

#endif  //  ISOLATEDHITMERGINGALGORITHM_H
