  /// \file ArborPluginManager.h
/*
 *
 * ArborPluginManager.h header template automatically generated by a class generator
 * Creation date : ven. mai 30 2014
 *
 * This file is part of ArborPFA libraries.
 * 
 * ArborPFA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * ArborPFA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with ArborPFA.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Ete Remi
 * @copyright CNRS , IPNL
 */


#ifndef ARBORPLUGINMANAGER_H
#define ARBORPLUGINMANAGER_H

// arborpfa
#include "arborpfa/arbor/ArborTypes.h"

// pandora
#include "Pandora/StatusCodes.h"

namespace arbor
{

/** 
 * @brief ArborPlugin class
 */ 
class ArborPluginManager
{
 protected:

	/**
	 * @brief Ctor
	 */
	ArborPluginManager();

	/**
	 * @brief Dtor
	 */
	virtual ~ArborPluginManager();

	/**
	 * @brief Register a new function to build trees
	 */
	pandora::StatusCode RegisterTreeBuilder(const std::string &treeBuilderName, ITreeBuilder *pTreeBuilder);

	/**
	 * @brief Set the current tree builder by name. Tree builder should be registered before
	 */
	pandora::StatusCode SetCurrentTreeBuilder(const std::string &treeBuilder);

	/**
	 * @brief Get the current tree builder
	 */
	pandora::StatusCode GetCurrentTreeBuilder(ITreeBuilder *&pTreeBuilder);

	/**
	 * @brief Get the current tree builder name
	 */
	pandora::StatusCode GetCurrentTreeBuilderName(std::string &treeBuilderName);

	/**
	 * @brief Register a new function to build branches
	 */
	pandora::StatusCode RegisterBranchBuilder(const std::string &branchBuilderName, IBranchBuilder *pBranchBuilder);

	/**
	 * @brief Set the current branch builder by name. Branch builder should be registered before
	 */
	pandora::StatusCode SetCurrentBranchBuilder(const std::string &branchBuilder);

	/**
	 * @brief Get the current tree builder
	 */
	pandora::StatusCode GetCurrentBranchBuilder(IBranchBuilder *&pBranchBuilder);

	/**
	 * @brief Get the current branch builder name
	 */
	pandora::StatusCode GetCurrentBranchBuilderName(std::string &branchBuilderName);

	// members
	TreeBuilderMap          m_treeBuilderMap;
	BranchBuilderMap        m_branchBuilderMap;

	ITreeBuilder           *m_pCurrentTreeBuilder;
	IBranchBuilder         *m_pCurrentBranchBuilder;
	std::string             m_currentTreeBuilderName;
	std::string             m_currentBranchBuilderName;

	// friendship
	friend class ArborContentApiImpl;
	friend class ArborApiImpl;
	friend class Arbor;
}; 

} 

#endif  //  ARBORPLUGINMANAGER_H
